=== grobmeier/piwi/piwi/resources/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://piwi.googlecode.com/xsd/config"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://piwi.googlecode.com/xsd/config">
	<element name="configuration" type="tns:configurationType">
	</element>
	<complexType name="configurationType">
		<sequence>
			<element name="cachetime" type="int" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="navigationGenerators" type="tns:navigationGeneratorsType"
				minOccurs="0" maxOccurs="1">
			</element>
			<element name="customXSLTStylesheet" type="string" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="authentication" type="tns:authenticationType"
				minOccurs="0" maxOccurs="1">
			</element>
			<element name="serializers" type="tns:serializersType"
				minOccurs="0" maxOccurs="1">
				<unique name="UniqueExtension">
					<selector xpath=".//tns:serializer" />
					<field xpath="@extension" />
				</unique>
			</element>
		</sequence>
	</complexType>
	<complexType name="authenticationType">
		<attribute name="enabled" type="boolean" use="required"></attribute>
		<attribute name="roleProvider" type="string" use="required"></attribute>
		<attribute name="loginPageId" type="string" use="required"></attribute>
	</complexType>
	<complexType name="serializersType">
		<sequence>
			<element name="serializer" type="tns:serializerType"
				minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="serializerType">
		<attribute name="extension" type="string" use="required"></attribute>
		<attribute name="serializer" type="string" use="required"></attribute>
	</complexType>
	<complexType name="navigationGeneratorType">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="class" type="string" use="required"></attribute>
		<attribute name="pageId" type="string" use="optional"></attribute>
		<attribute name="depth" type="int" use="optional"></attribute>
		<attribute name="includeParent" type="boolean" use="optional"></attribute>
	</complexType>



	<complexType name="navigationGeneratorsType">
		<sequence>
			<element name="navigationGenerator" type="tns:navigationGeneratorType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
</schema>

=== grobmeier/piwi/piwi/custom/content/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://piwi.googlecode.com/xsd/config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://piwi.googlecode.com/xsd/config ../../resources/xsd/config.xsd">
	
	<!-- 
	   The timespan in seconds after which a page will be regenerated.
	   Set to '0' to disable the CACHE.
	 -->
	<cachetime>0</cachetime>
	
   <!-- 
      Configuration of the NAVIGATION-GENERATORSs that should be instantiated.
      They will be instantiated with the given name, so you could easily embed them in your templates.
    -->
   <navigationGenerators>
      <navigationGenerator name="HTML_NAVIGATION" class="SimpleTextNavigationGenerator" depth="1" includeParent="1" />
      <navigationGenerator name="SITE_MAP_PATH" class="SiteMapPathNavigationGenerator" pageId="CURRENT_PAGE" />
   </navigationGenerators>
	
	<!-- 
      The xml file containing LABELs. Use this file to specify internationalized
      text. Which can be used in Generators and StepProcessors.
    -->
   <customLabels>custom/resources/labels/labels.xml</customLabels>
   
	<!-- 
	   A custom XSLTSTYLESHEET which will be included in the serialization process.
	   Use this to perfom custom transformations.
	 -->
	<customXSLTStylesheet>custom/resources/xslt/CustomTransformation.xsl</customXSLTStylesheet>
	
	<!-- 
	   Here you can enable/disable AUTHENTICATION.
	   The 'roleProvider' is the class used for the authentication.
	   The 'loginPageId' is the ID of the page being displayed when authentication is required.
	   To protect pages set the roles in the 'site.xml'.
	 -->
	<authentication enabled="1" roleProvider="SampleRoleProvider"
		loginPageId="login" />
		
	<!--
		Configuration of the SERIALIZERs.
		If no serializer for a extension is specified, the default serializer will be used.
		To embed a custom serializer specify the extension and the classname of the serializer.
		If you add a new extension you also have to adjust the '.htaccess' file in the root folder.
	 -->
	<serializers>
		<serializer extension="html" serializer="HTMLSerializer" />
		<serializer extension="pdf" serializer="PDFSerializer" />
		<serializer extension="xml" serializer="PiwiXMLSerializer" />
		<serializer extension="doc" serializer="WordSerializer" />
		<serializer extension="xls" serializer="ExcelSerializer" />		
	</serializers>
</configuration>
