=== grobmeier/piwi/piwi/resources/xsd/context.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://piwi.googlecode.com/xsd/context"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://piwi.googlecode.com/xsd/context">
	<complexType name="beanType">

        <choice minOccurs="0" maxOccurs="unbounded">
			<element name="constructor-args" type="tns:contructorArgsType" minOccurs="0" maxOccurs="1">
			</element>
		</choice>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="class" type="string" use="required"></attribute>

		<attribute name="singleton" type="boolean"></attribute>

	</complexType>
	<element name="context" type="tns:contextType">
		<unique name="UniqueBeanId">
			<selector xpath=".//tns:bean" />
			<field xpath="@id" />
		</unique>
	</element>
	<complexType name="contextType">
		<sequence>
			<element name="bean" type="tns:beanType" minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>		
	</complexType>



	<complexType name="beanRefType">
		<attribute name="ref" type="string" use="required"></attribute>
	</complexType>

	<complexType name="contructorArgsType">
        <choice minOccurs="0" maxOccurs="unbounded">
			<element name="arg" type="string"></element>
			<element name="bean" type="tns:beanRefType"></element>
		</choice>
	</complexType>
</schema>

=== grobmeier/piwi/test/unit/lib/piwi/beanfactory/data/additionalContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<context xmlns="http://piwi.googlecode.com/xsd/context" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://piwi.googlecode.com/xsd/context ../../../../../../piwi/resources/xsd/context.xsd">

    <bean id="testObject2" class="TestObject2" scope="request">
        <constructor-args>
            <arg>test_string2</arg>
            <arg>0</arg>
            <arg>0777</arg>
            <arg>45.6</arg>
        </constructor-args>
    </bean>

    <bean id="testObject4" class="TestObject1" scope="prototype">
        <property name="fasel" php="$GLOBALS['TEST'].CONTENT_TEST" />
    </bean>
</context>
