=== grobmeier/piwi/piwi/resources/xsd/forms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://piwi.googlecode.com/xsd/forms"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://piwi.googlecode.com/xsd/forms">
	<complexType name="formType">
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="path" type="string" use="required"></attribute>
	</complexType>
	<element name="forms" type="tns:formsType">
		<unique name="UniqueFormId">
			<selector xpath=".//tns:form" />
			<field xpath="@id" />
		</unique>
	</element>
	<complexType name="formsType">
		<sequence>
			<element name="form" type="tns:formType" minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>		
	</complexType>
</schema>

=== grobmeier/piwi/piwi/custom/content/forms.xml
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns="http://piwi.googlecode.com/xsd/forms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://piwi.googlecode.com/xsd/forms ../../resources/xsd/forms.xsd">
	<language region="default">
		<form id="wizardform" href="custom/content/en/features/forms/wizardform.xml" />
		<form id="validatorform" href="custom/content/en/features/forms/validatorform.xml" />
		<form id="loginform" href="custom/content/en/forms/loginform.xml" />
		<form id="logoutform" href="custom/content/en/forms/logoutform.xml" />
	</language>
	<language region="de">
		<form id="wizardform" href="custom/content/de/features/forms/wizardform.xml" />
		<form id="validatorform" href="custom/content/de/features/forms/validatorform.xml" />
		<form id="loginform" href="custom/content/de/forms/loginform.xml" />
		<form id="logoutform" href="custom/content/de/forms/logoutform.xml" />
	</language>
</forms>
